name: maven

on:
  push:
    branches:
      - main
      - snapshot-*
    paths-ignore:
      - '.github/workflows/release.yml'
      - 'README.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      - uses: dbstar-org/setup-maven@main
      - run: cat ~/.m2/settings.xml
      - run: echo 'version is ${{ matrix.version }}'