name: maven

on:
  push:
    branches:
      - main
      - snapshot-*
    paths-ignore:
      - '.github/workflows/release.yml'
      - 'README.md'
  workflow_dispatch:

jobs:
  maven:
    permissions:
      packages: write
    uses: dbstar-org/general/.github/workflows/maven.yml@main
    with:
      SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}