name: maven

on:
  push:
    branches:
      - main
      - snapshot-*
    paths-ignore:
      - '.github/workflows/release.yml'
      - 'README.md'
  workflow_dispatch:

jobs:
  maven:
    permissions:
      packages: write
    uses: dbstarll/general/.github/workflows/maven.yml@main
    secrets: inherit