name: release

on: workflow_dispatch

jobs:
  release:
    permissions:
      contents: write
      packages: write
    uses: dbstar-org/general/.github/workflows/maven-release.yml@main
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
      OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}